# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0122_assessment_id_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentnode',
            name=b'assessment_id_idx',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='included_languages',
        ),
        migrations.AddField(
            model_name='channel',
            name='course_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='assessmentitem',
            index=models.Index(fields=[b'assessment_id'], name=b'assessment_id_idx'),
        ),
    ]
