# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0123_auto_20201003_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='included_languages',
            field=models.ManyToManyField(blank=True, related_name='channels', to='contentcuration.Language', verbose_name=b'languages'),
        ),
    ]
