# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0124_channel_included_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='apps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='learning_style',
            field=models.CharField(choices=[(b'AC', b'Activist'), (b'RE', b'Reflector'), (b'TH', b'Theorist'), (b'PR', b'Pragmatist'), (b'KI', b'Kinestic'), (b'AU', b'Auditory')], default=b'AC', max_length=2),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
