# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0125_auto_20201003_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('correct_answer', models.BooleanField()),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='answers',
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='assessment_category',
            field=models.CharField(choices=[(b'HW', b'Homework'), (b'CW', b'Classwork'), (b'T', b'Test'), (b'IW', b'Individualwork'), (b'GW', b'Groupwoek')], default=b'HW', max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='difficulity',
            field=models.CharField(choices=[(b'E', b'Easy'), (b'M', b'Medium'), (b'H', b'Hard')], default=b'E', max_length=10),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contentcuration.AssessmentItem'),
        ),
    ]
